import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const data = JSON.parse(readFileSync(new URL('programs.json', import.meta.url), 'utf8'));
const template = readFileSync(new URL('template.html', import.meta.url), 'utf8');
const esc = s => s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
for (const p of data) {
  const description = esc(p.lead + ' – ' + p.rest + '. ' + p.audience);
  let html = template
    .replaceAll('{{number}}', String(p.number))
    .replaceAll('{{sessions}}', String(p.sessions))
    .replace(/<!-- Generated[\s\S]*?-->/, '<!-- Generated by program-template/build.mjs. Edit programs.json and template.html. -->')
    .replace(/ data-ilead-[a-z]+="[^"]*"/g, '')
    .replace(/ data-ilead-(cta|back)/g, '')
    .replace(/<link rel="canonical"[^>]+>\n?/g, '')
    .replace(/<meta property="og:(url|image)"[^>]+>\n?/g, '')
    .replace(/<script[^>]*ilead-nav[^>]*><\/script>/, '<script src="../../assets/programs/program.js" defer></script>')
    .replace(/iLEAD 1/g, 'iGLOBAL ' + p.number)
    .replace(/Tiếng Anh tiểu học Pre-A1/g, 'Tiếng Anh THCS ' + p.level)
    .replace(/tiểu học/g, 'THCS')
    .replace(/iSMART Young Explorers/g, 'iSMART Global Achievers')
    .replace(/content="Khởi đầu tự tin[^"]*"/g, 'content="' + description + '"')
    .replaceAll('../../uploads/ismart-2026-logo.png', '../../assets/ismart-logo-header.png')
    .replace(/..\/..\/uploads\/ilead-program.css\?[^"]+/, '../../assets/programs/program.css')
    .replace(/&amp;icon_names=[^&]+/, '')
    .replaceAll('../../#gia-tri', '../../#ket-qua')
    .replaceAll('../../#trai-nghiem', '../../#he-sinh-thai')
    .replace(/src="..\/..\/uploads\/ilead-banner-1.png" width="1672" height="941" alt="[^"]+"/,
      'src="../../assets/programs/' + p.banner + '" srcset="../../assets/programs/iglobal-' + p.number + '-banner-960.webp 960w, ../../assets/programs/' + p.banner + ' 1664w" sizes="(max-width: 860px) 100vw, 1000px" width="1664" height="951" alt="' + esc(p.alt) + '"')
    .replace('<span class="lp-title-brand">iLEAD</span> <span class="lp-title-num">1</span>', '<span class="lp-title-brand">iGLOBAL</span> <span class="lp-title-num">' + p.number + '</span>')
    .replace('<strong>Pre-A1</strong>', '<strong>' + p.level + '</strong>')
    .replace(/<p class="lp-tagline">[\s\S]*?<\/p>/, '<p class="lp-tagline"><span class="lp-tagline-lead">' + esc(p.lead) + '</span><span class="lp-sr"> – </span><span class="lp-tagline-rest">' + esc(p.rest) + '</span></p>')
    .replace(/<ol class="lp-topic-grid">[\s\S]*?<\/ol>/, '<ol class="lp-topic-grid">' + p.topics.map((t,i) => '<li class="lp-topic"><span class="lp-topic-icon lp-tone-' + (i+1) + '" aria-hidden="true"><span class="material-symbols-rounded">' + p.icons[i] + '</span></span><span class="lp-topic-text">' + esc(t) + '</span></li>').join('\n') + '</ol>')
    .replace(/<ul class="lp-benefit-grid">[\s\S]*?<\/ul>/, '<ul class="lp-benefit-grid">' + p.benefits.map((t,i) => '<li class="lp-benefit"><span class="lp-benefit-icon lp-benefit-icon--' + (i+1) + '" aria-hidden="true"><span class="material-symbols-rounded">' + ['school','bar_chart','forum','trending_up'][i] + '</span></span><span class="lp-benefit-text">' + esc(t) + '</span></li>').join('\n') + '</ul>')
    .replace(/<p class="lp-audience-text">[\s\S]*?<\/p>/, '<p class="lp-audience-text">' + esc(p.audience) + '</p>');
  mkdirSync(root + 'chuong-trinh/' + p.slug, { recursive: true });
  writeFileSync(root + 'chuong-trinh/' + p.slug + '/index.html', html);
}
console.log('Built 4 iGLOBAL program pages.');
